### ISSUE TITLE
在Github上开发便于社区协作？

### ISSUE THREAD

**Issue by firede** [Clouda-team/touchjs#1]
有些地方想提pull request（比如无全局变量的AMD支持），但现在github放的只是release。
可以考虑直接在github上运作项目，便于社区协作与变更点的跟踪。

**Comment by tongyao** [comment]
谢雷哥建议，说的很对，我们想想办法从内部GIT上搬出来。

不过在我们搞定之前，你看要不先在0.2.11上把你的pull request提给我们？

**Comment by huang-xin** [comment]
非常感谢, 我马上开始着手这件事情.
